.

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -41,7 +41,7 @@ jobs:
         run: |
           chmod +x ./scripts/linux-setup.sh
           ./scripts/linux-setup.sh
-          sudo /usr/bin/Xvfb $DISPLAY -screen 0 1280x1024x24 &
+          # sudo /usr/bin/Xvfb $DISPLAY -screen 0 1280x1024x24 &
 
       - name: Remove problematic brew libs (see Nuitka/Nuitka#2853)
         if: runner.os == 'macOS' && runner.arch != 'ARM64'
@@ -66,26 +66,27 @@ jobs:
         run: |
           brew install coreutils
           echo "Checking dependencies"
-          echo "gtimeout 10 ${{ steps.build-exe.outputs.out-filepath }}" | bash || true
-          ls build -ltraR |egrep -v '\.$|\.\.|\.:|\.\/|total|^d' |sed '/^$/d' || true
+          echo "gtimeout 10 ${{ steps.build-exe.outputs.out-filepath }}" | bash
+          # ls build -ltraR |egrep -v '\.$|\.\.|\.:|\.\/|total|^d' |sed '/^$/d' || true
 
-      - name: Test executable [Linux, Windows]
-        id: test-exe
-        if: runner.os != 'macOS'
+      - name: Test executable [Windows]
+        if: runner.os == 'Windows'
         shell: bash
         run: |
           echo "Checking dependencies"
-          echo "timeout 30 ${{ steps.build-exe.outputs.out-filepath }}" | bash || true
-          echo "ldd ${{ steps.build-exe.outputs.out-filepath }}" | bash
-          ls build -ltraR |egrep -v '\.$|\.\.|\.:|\.\/|total|^d' |sed '/^$/d' || true
+          echo "timeout 30 ${{ steps.build-exe.outputs.out-filepath }}" | bash
+          # echo "ldd ${{ steps.build-exe.outputs.out-filepath }}" | bash
+          # ls build -ltraR |egrep -v '\.$|\.\.|\.:|\.\/|total|^d' |sed '/^$/d' || true
 
-      - name: Set Linux exe path
+      - name: est executable [Linux]
         id: set-path
         if: runner.os == 'Linux'
         shell: bash
         run: |
           echo "path=${{ steps.build-exe.outputs.out-filename }}" >> "$GITHUB_OUTPUT"
           sudo apt-get install libtree
+          echo "Checking dependencies"
+          echo "timeout 30 ${{ steps.build-exe.outputs.out-filepath }}" | bash
           libtree /home/runner/.cache/TiLiA/0.5.15.1/PySide6/qt-plugins/platforms/libqxcb.so
 
       - name: Upload executable
@@ -124,16 +125,14 @@ jobs:
                 then
                   echo "Linux works in a clean environment!";
               else
-                echo "Linux didn't work... Check libraries with previous step?" &&
-                echo "ldd build/ubuntu/exe/${{ needs.build.outputs.linux-build }}" | bash || echo "Couldn't get libraries";
+                echo "Linux didn't work... Check libraries with previous step?";
               fi;
           else
             echo "file not found!";
           fi
-          ls build -ltraR |egrep -v '\.$|\.\.|\.:|\.\/|total|^d' |sed '/^$/d' || true
+          echo "Missing libraries:"
           ldd /home/runner/.cache/TiLiA/0.5.15.1/PySide6/qt-plugins/platforms/libqxcb.so | grep "not found"
-          sudo apt-get install libtree
-          libtree /home/runner/.cache/TiLiA/0.5.15.1/PySide6/qt-plugins/platforms/libqxcb.so
+          ls build -ltraR |egrep -v '\.$|\.\.|\.:|\.\/|total|^d' |sed '/^$/d' || true
 
       - name: Upload
         uses: "softprops/action-gh-release@v2"
